swagger: "2.0"

info:
  title: "S-Leaf"
  version: "1.0"

host: "sleaf.endpoints.daun-314815.cloud.goog"

schemes:
  - "http"

paths:
  "/":
    get:
      description: "Greeting"
      operationId: "home"
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "Client error."
  
  "/random":
    get:
      description: "Get random plant info."
      operationId: "random"
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "Client error."
    
  "/all":
    get:
      description: " Get all info."
      operationId: "all"
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "Client error."

  "/upload":
    post:
      description: "Upload and get predict"
      operationId: "upload"
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "Client error."